enum WorkerCmdType
{
  WRKCMD_FIRST_FRONTEND = 0,
  WRKCMD_UPDATE_FX_SPOT_LIGHT = 0,
  WRKCMD_UPDATE_FX_NON_DEPENDENT,
  WRKCMD_UPDATE_FX_REMAINING,
  WRKCMD_DPVS_CELL_STATIC,
  WRKCMD_DPVS_CELL_SCENE_ENT,
  WRKCMD_DPVS_CELL_DYN_MODEL,
  WRKCMD_DPVS_CELL_DYN_BRUSH,
  WRKCMD_DPVS_ENTITY,
  WRKCMD_ADD_SCENE_ENT,
  WRKCMD_SPOT_SHADOW_ENT,
  WRKCMD_SHADOW_COOKIE,
  WRKCMD_BOUNDS_ENT_DELAYED,
  WRKCMD_SKIN_ENT_DELAYED,
  WRKCMD_GENERATE_FX_VERTS,
  WRKCMD_GENERATE_MARK_VERTS,
  WRKCMD_SKIN_CACHED_STATIC_MODEL,
  WRKCMD_SKIN_XMODEL,
  WRKCMD_COUNT
};

