#ifndef PHYSICS_ODE_INCLUDE_ODE_IW_DEFINITIONS_H
#define PHYSICS_ODE_INCLUDE_ODE_IW_DEFINITIONS_H

enum PhysWorld
{
  PHYS_WORLD_DYNENT,
  PHYS_WORLD_FX,
  PHYS_WORLD_RAGDOLL,
  PHYS_WORLD_COUNT
};

#endif